## Deliverable 2. Create a Customer Travel Destinations Map.

In [ ]:
# pip install gmaps

In [8]:
# Dependencies and Setup
import pandas as pd
import gmaps
import requests

# Import API key

from config import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [9]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("Weather_Database/WeatherPy_database.csv")
city_data_df

,City_ID,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Weather Description
0,0,Joao Pinheiro,-17.7425,-46.1725,64.20,52,0,7.11,BR,clear sky
1,1,Tuatapere,-46.1333,167.6833,48.13,75,6,4.07,NZ,clear sky
2,2,Mataura,-46.1927,168.8643,46.47,89,68,1.19,NZ,broken clouds
3,3,Bluff,-46.6000,168.3333,46.80,71,61,7.05,NZ,broken clouds
4,4,Derzhavinsk,51.1000,66.3167,73.78,52,100,10.83,KZ,overcast clouds
...,...,...,...,...,...,...,...,...,...,...
715,715,Puerto Del Rosario,28.5004,-13.8627,69.55,78,100,19.57,ES,overcast clouds
716,716,Festus,38.2206,-90.3960,74.75,87,0,5.68,US,clear sky
717,717,Chunoyar,57.4467,97.3217,67.98,64,100,3.83,RU,overcast clouds
718,718,Marevo,57.3146,32.0804,51.15,92,80,4.14,RU,broken clouds
719,719,Severomuysk,56.1481,113.4267,60.71,46,23,8.14,RU,few clouds

In [10]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 

min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 75
What is the maximum temperature you would like for your trip? 85

In [11]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.

preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df

,City_ID,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Weather Description
22,22,Benghazi,32.1167,20.0667,75.58,52,0,5.37,LY,clear sky
24,24,Bintulu,3.1667,113.0333,84.61,79,40,2.30,MY,scattered clouds
28,28,Katsuura,35.1333,140.3000,75.45,85,100,16.87,JP,overcast clouds
32,32,Luwuk,-0.9516,122.7875,80.92,78,99,4.56,ID,overcast clouds
33,33,Bengkulu,-3.8004,102.2655,79.41,85,60,10.54,ID,broken clouds
...,...,...,...,...,...,...,...,...,...,...
702,702,Atasu,48.6814,71.6433,84.52,22,100,9.19,KZ,overcast clouds
704,704,Lorengau,-2.0226,147.2712,82.11,75,40,4.41,PG,scattered clouds
707,707,Atar,20.5169,-13.0499,77.72,77,99,5.19,MR,moderate rain
711,711,Monrovia,6.3005,-10.7969,76.91,78,8,2.39,LR,clear sky
713,713,Pishin,30.5803,66.9961,80.38,14,0,8.37,PK,clear sky

In [12]:
# 4a. Determine if there are any empty rows.
preferred_cities_df.count()

City_ID                185
City                   185
Lat                    185
Lng                    185
Max Temp               185
Humidity               185
Cloudiness             185
Wind Speed             185
Country                185
Weather Description    185
dtype: int64

In [13]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.
clean_df = preferred_cities_df.dropna()
clean_df

,City_ID,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Weather Description
22,22,Benghazi,32.1167,20.0667,75.58,52,0,5.37,LY,clear sky
24,24,Bintulu,3.1667,113.0333,84.61,79,40,2.30,MY,scattered clouds
28,28,Katsuura,35.1333,140.3000,75.45,85,100,16.87,JP,overcast clouds
32,32,Luwuk,-0.9516,122.7875,80.92,78,99,4.56,ID,overcast clouds
33,33,Bengkulu,-3.8004,102.2655,79.41,85,60,10.54,ID,broken clouds
...,...,...,...,...,...,...,...,...,...,...
702,702,Atasu,48.6814,71.6433,84.52,22,100,9.19,KZ,overcast clouds
704,704,Lorengau,-2.0226,147.2712,82.11,75,40,4.41,PG,scattered clouds
707,707,Atar,20.5169,-13.0499,77.72,77,99,5.19,MR,moderate rain
711,711,Monrovia,6.3005,-10.7969,76.91,78,8,2.39,LR,clear sky
713,713,Pishin,30.5803,66.9961,80.38,14,0,8.37,PK,clear sky

In [14]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = clean_df[["City", "Country", "Max Temp", "Weather Description", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df

,City,Country,Max Temp,Weather Description,Lat,Lng,Hotel Name
22,Benghazi,LY,75.58,clear sky,32.1167,20.0667,
24,Bintulu,MY,84.61,scattered clouds,3.1667,113.0333,
28,Katsuura,JP,75.45,overcast clouds,35.1333,140.3000,
32,Luwuk,ID,80.92,overcast clouds,-0.9516,122.7875,
33,Bengkulu,ID,79.41,broken clouds,-3.8004,102.2655,
...,...,...,...,...,...,...,...
702,Atasu,KZ,84.52,overcast clouds,48.6814,71.6433,
704,Lorengau,PG,82.11,scattered clouds,-2.0226,147.2712,
707,Atar,MR,77.72,moderate rain,20.5169,-13.0499,
711,Monrovia,LR,76.91,clear sky,6.3005,-10.7969,
713,Pishin,PK,80.38,clear sky,30.5803,66.9961,

In [18]:
# Print the beginning of the logging.
# print("Beginning Data Retrieval     ")
# print("-----------------------------")

# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

# 6b. Iterate through the hotel DataFrame.
for index, row in hotel_df.iterrows():
    
    # 6c. Get latitude and longitude from DataFrame
    
    lat = row["Lat"]
    lng = row["Lng"]
    
    # Add the latitude and longitude to location key for the params dictionary.
    params["location"] = f"{lat},{lng}"
    #print(params)
    
    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # 6e. Make request and retrieve the JSON data from the search. 
    hotels = requests.get(base_url, params=params).json()
    #print(hotels)
    
  
    
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.  
    try:
        print(f"At index:{index} hotel name is")
        print(hotels["results"][0]["name"])
        print("-------------------------")
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping")
        pass

# Indicate that Data Loading is complete.
print("-----------------------------")
print("Data Retrieval Complete      ")
print("-----------------------------")

At index:22 hotel name is
Tibesti Hotel
-------------------------
At index:24 hotel name is
900 Boutique INN
-------------------------
At index:28 hotel name is
Katsuura Hotel Mikazuki
-------------------------
At index:32 hotel name is
Hotel Santika Luwuk
-------------------------
At index:33 hotel name is
Grage Hotel Bengkulu
-------------------------
At index:35 hotel name is
Taloa Heights
-------------------------
At index:38 hotel name is
Paradise Inn
-------------------------
At index:39 hotel name is
Villa Enata
-------------------------
At index:42 hotel name is
Will T Place
-------------------------
At index:59 hotel name is
فندق ربك Rabak Hotel
-------------------------
At index:60 hotel name is
Hamza hotel jiwani
-------------------------
At index:64 hotel name is
HAMDAN PLAZA HOTEL SALALAH, an HTG Hotel
-------------------------
At index:67 hotel name is
Isles Sunset Lodge
-------------------------
At index:72 hotel name is
Macs
-------------------------
At index:73 hotel name is
LT Aparthotel
-------------------------
At index:87 hotel name is
Keleti Beach Resort
-------------------------
At index:88 hotel name is
صاحبة الفخامة
-------------------------
At index:89 hotel name is
خوابگاه آبجی محدثه
-------------------------
At index:94 hotel name is
Sítio Blasi
-------------------------
At index:98 hotel name is
Huanghai Hotel
-------------------------
At index:104 hotel name is
Red Sea Resort & Suites Mandera County
-------------------------
At index:105 hotel name is
Bora-Bora Pearl Beach Resort & Spa
-------------------------
At index:107 hotel name is
Trinity Plains Tourist Park
-------------------------
At index:116 hotel name is
Sheraton Kauai Coconut Beach Resort
-------------------------
At index:127 hotel name is
Hotel Limonar
-------------------------
At index:128 hotel name is
HS Hotsson Smart Acapulco
-------------------------
At index:129 hotel name is
Posada Lilia
-------------------------
At index:130 hotel name is
VS Villa
-------------------------
At index:132 hotel name is
Pension Oaoa
-------------------------
At index:136 hotel name is
Ashoka Lodge
-------------------------
At index:140 hotel name is
Hilo Hawaiian Hotel
-------------------------
At index:147 hotel name is
InterContinental Riyadh, an IHG Hotel
-------------------------
At index:152 hotel name is
Apel'sin
-------------------------
At index:165 hotel name is
HOTEL QUINTA ANTIGUA
-------------------------
At index:170 hotel name is
Hampton Inn & Suites Natchez
-------------------------
At index:172 hotel name is
Villas de Puerto Viejo
-------------------------
At index:175 hotel name is
Park Pobedy
-------------------------
At index:177 hotel name is
Ecos Hotel Conforto
-------------------------
At index:180 hotel name is
Kashiwa Roman-sō
-------------------------
At index:181 hotel name is
Bonthe Holiday Village
-------------------------
At index:182 hotel name is
Derogongan Residence
-------------------------
At index:193 hotel name is
Sea Lounge! Bar, Club & Restaurant
-------------------------
At index:197 hotel name is
Khoniker Atithi
-------------------------
At index:204 hotel name is
Hotel not found... skipping
At index:205 hotel name is
Scoop Guest House
-------------------------
At index:212 hotel name is
Burntwood Hotel
-------------------------
At index:215 hotel name is
Nusa Island Retreat
-------------------------
At index:217 hotel name is
Grand Palladium Jamaica Resort & Spa
-------------------------
At index:224 hotel name is
Hotel not found... skipping
At index:225 hotel name is
hotel la terminal
-------------------------
At index:227 hotel name is
ООО "Туруханская пушнина"
-------------------------
At index:228 hotel name is
Conrad Bora Bora Nui
-------------------------
At index:244 hotel name is
ALETHEIA Appartement Sinnamary
-------------------------
At index:247 hotel name is
Niyama Private Islands Maldives
-------------------------
At index:248 hotel name is
Leumerus Bungalows
-------------------------
At index:249 hotel name is
ibis Styles Mt Isa Verona
-------------------------
At index:250 hotel name is
Hotel Tesoro Los Cabos
-------------------------
At index:253 hotel name is
Best Western Plus Abbey Inn
-------------------------
At index:257 hotel name is
Rtsm Shetpe Analog
-------------------------
At index:260 hotel name is
Mantra Trilogy Cairns
-------------------------
At index:271 hotel name is
Hotel not found... skipping
At index:273 hotel name is
Mystic Sands Beachfront Accommodation
-------------------------
At index:274 hotel name is
Aldea del Bazar Hotel and Spa
-------------------------
At index:276 hotel name is
ibis Styles Karratha
-------------------------
At index:277 hotel name is
El rranchito michuacan de ocampos
-------------------------
At index:280 hotel name is
Fortuna Ranch
-------------------------
At index:284 hotel name is
Hôtel Le Dronmi
-------------------------
At index:290 hotel name is
Hotel Nusantara I
-------------------------
At index:291 hotel name is
Grand Vilia Hotel
-------------------------
At index:293 hotel name is
Honglin Guesthouse
-------------------------
At index:296 hotel name is
Mega Hotel, Miri
-------------------------
At index:304 hotel name is
Tianlun Tanxianglou Hotel
-------------------------
At index:305 hotel name is
Hotel not found... skipping
At index:308 hotel name is
المنزل
-------------------------
At index:316 hotel name is
Pousada Joaci
-------------------------
At index:318 hotel name is
Meadows
-------------------------
At index:321 hotel name is
SHARMA HOTEL( CHANDURIA)
-------------------------
At index:324 hotel name is
HOTEL Posada La Regia
-------------------------
At index:325 hotel name is
Uruna Bay Retreat
-------------------------
At index:327 hotel name is
COP Monti
-------------------------
At index:331 hotel name is
AUBERGE MAQUIS RESTO CAFE LE ROUTIER PLUS
-------------------------
At index:346 hotel name is
African House Resort
-------------------------
At index:348 hotel name is
محمد هادي ال فطيح
-------------------------
At index:366 hotel name is
Seydi oteli
-------------------------
At index:368 hotel name is
Dhulikhel Lodge Resort
-------------------------
At index:369 hotel name is
Kost Pria
-------------------------
At index:370 hotel name is
Aldan Guest House
-------------------------
At index:373 hotel name is
Pausada Morabedja
-------------------------
At index:374 hotel name is
A Beach Retreat On Casey Key
-------------------------
At index:378 hotel name is
Vahmoneh Lodge Vanimo
-------------------------
At index:387 hotel name is
Auki Motel
-------------------------
At index:390 hotel name is
Niamat parda Center chaman
-------------------------
At index:392 hotel name is
Sea Star Beau Rivage Hotel
-------------------------
At index:396 hotel name is
RANCHO DE LUCIA
-------------------------
At index:401 hotel name is
Ikathouse
-------------------------
At index:405 hotel name is
Four Points by Sheraton Punta Gorda Harborside
-------------------------
At index:406 hotel name is
Pudong Holiday Hotel
-------------------------
At index:409 hotel name is
Vaishali Comforts
-------------------------
At index:417 hotel name is
Marriott's Ko Olina Beach Club
-------------------------
At index:418 hotel name is
Hotel not found... skipping
At index:419 hotel name is
ZINGARA 76ft Catamaran, full crew-all included
-------------------------
At index:424 hotel name is
Railway motel
-------------------------
At index:426 hotel name is
Hotel y restaurante "El Diamante"
-------------------------
At index:427 hotel name is
Xichang ibis Hotel
-------------------------
At index:431 hotel name is
Hôtel Trois Étoiles de Biltine
-------------------------
At index:434 hotel name is
Bungalow 63
-------------------------
At index:437 hotel name is
Hotel Fellip
-------------------------
At index:445 hotel name is
Screensaver
-------------------------
At index:446 hotel name is
Shishime Hotel
-------------------------
At index:449 hotel name is
Storyboard Beach Resort
-------------------------
At index:453 hotel name is
Trump International Hotel & Tower Panama
-------------------------
At index:456 hotel name is
Hotel RIKMAN Continental
-------------------------

At index:460 hotel name is
Le Méridien Re-Ndama
-------------------------
At index:467 hotel name is
Hotel not found... skipping
At index:468 hotel name is
Idlers' Rest Beach Hotel
-------------------------
At index:473 hotel name is
Windsor Inn & Suites
-------------------------
At index:479 hotel name is
Casa de Retiro Preciosinas
-------------------------
At index:480 hotel name is
Goto Guesthouse Utojuku & SA Car Rental
-------------------------
At index:485 hotel name is
CeBlue Villas & Beach Resort
-------------------------
At index:493 hotel name is
JABIR HOTEL
-------------------------
At index:495 hotel name is
Calypso Cove
-------------------------
At index:507 hotel name is
Gaytari Got Form
-------------------------
At index:508 hotel name is
Tanna Lodge
-------------------------
At index:512 hotel name is
castelo pizzaria
-------------------------
At index:514 hotel name is
Iglesia morava renovada
-------------------------
At index:517 hotel name is
Jade Garden
-------------------------
At index:520 hotel name is
Kashmiri Hotal
-------------------------
At index:524 hotel name is
hotêl doufoulougou
-------------------------
At index:527 hotel name is
El Medina
-------------------------
At index:536 hotel name is
Expeditions Ténére voyages
-------------------------
At index:537 hotel name is
Divi Flamingo Beach Resort & Casino
-------------------------
At index:539 hotel name is
Assaleh Hamdan Haroune
-------------------------
At index:540 hotel name is
Al-bustan Hotel And Restaurant.
-------------------------
At index:543 hotel name is
Ramkota Hotel
-------------------------
At index:555 hotel name is
Maui Seaside Hotel
-------------------------
At index:560 hotel name is
Motel 6 Santa Ana, CA
-------------------------
At index:563 hotel name is
Erenhot Rurouni Youth Hostel
-------------------------
At index:564 hotel name is
In Wewak Boutique Hotel
-------------------------
At index:573 hotel name is
Hotel not found... skipping
At index:579 hotel name is
Hotel Edi
-------------------------
At index:582 hotel name is
Cottege near Ufa
-------------------------
At index:586 hotel name is
Corrêa Hotel
-------------------------
At index:589 hotel name is
Hotel not found... skipping
At index:591 hotel name is
Courtyard by Marriott Lincoln Downtown/Haymarket
-------------------------
At index:592 hotel name is
Hotel Juba
-------------------------
At index:594 hotel name is
Makai Beach Lodge
-------------------------
At index:596 hotel name is
Hotel Posada San Jose
-------------------------
At index:597 hotel name is
Haajy Guest House 1
-------------------------
At index:598 hotel name is
Holiday Inn & Suites Hulunbuir
-------------------------
At index:601 hotel name is
Umit
-------------------------
At index:603 hotel name is
Svet V Okne
-------------------------
At index:611 hotel name is
Ungoofaaru Inn
-------------------------
At index:612 hotel name is
Hotel Memory
-------------------------
At index:615 hotel name is
Villa Park Hotel | Natal
-------------------------
At index:616 hotel name is
Ha'apai Beach Resort
-------------------------
At index:620 hotel name is
Grand 0773 Hotel
-------------------------
At index:623 hotel name is
Kamaneahn Hotel Inc
-------------------------
At index:624 hotel name is
Yos ega cv
-------------------------
At index:629 hotel name is
Holiday Inn Express & Suites Elk Grove Central - Hwy 99, an IHG Hotel
-------------------------
At index:633 hotel name is
Americas Best Value Inn & Suites Harrisonville
-------------------------
At index:635 hotel name is
Divi Village Golf & Beach Resort
-------------------------
At index:636 hotel name is
ProDAF/Diffa
-------------------------
At index:638 hotel name is
Sahid Bela Ternate Hotel
-------------------------
At index:641 hotel name is
Wanhao Hotel
-------------------------
At index:647 hotel name is
Hotel not found... skipping
At index:649 hotel name is
LE SAMANA
-------------------------
At index:652 hotel name is
Guest Hotel
-------------------------
At index:655 hotel name is
Simple Rewards
-------------------------
At index:658 hotel name is
Shuangliu Love Home Business Hotel
-------------------------
At index:668 hotel name is
Plaza Hotel & Casino
-------------------------
At index:669 hotel name is
ROOM # 105 DUBAI HOTEL ZHOB
-------------------------
At index:673 hotel name is
Motel 6 Barstow, CA
-------------------------
At index:674 hotel name is
Hotel Zaraza
-------------------------
At index:687 hotel name is
Castle Comfort Lodge Dive Dominica
-------------------------
At index:688 hotel name is
Hotel Arena Blanca
-------------------------
At index:692 hotel name is
فندق أوباري
-------------------------
At index:693 hotel name is
GreenTree Inn Linxia Autonomous Prefecture Linxia Oxford River Avenue Express Hotel
-------------------------
At index:697 hotel name is
Hotel Toubal
-------------------------
At index:698 hotel name is
롯데호텔 서울
-------------------------
At index:701 hotel name is
Hilton Garden Inn Qidong
-------------------------
At index:702 hotel name is
Dostyk
-------------------------
At index:704 hotel name is
Lorengau Harbourside Hotel
-------------------------
At index:707 hotel name is
Oumou Elghoura
-------------------------
At index:711 hotel name is
Sunset Inn
-------------------------
At index:713 hotel name is
City Hotel Pishin
-------------------------
-----------------------------
Data Retrieval Complete
-----------------------------

In [19]:
hotel_df

,City,Country,Max Temp,Weather Description,Lat,Lng,Hotel Name
22,Benghazi,LY,75.58,clear sky,32.1167,20.0667,Tibesti Hotel
24,Bintulu,MY,84.61,scattered clouds,3.1667,113.0333,900 Boutique INN
28,Katsuura,JP,75.45,overcast clouds,35.1333,140.3000,Katsuura Hotel Mikazuki
32,Luwuk,ID,80.92,overcast clouds,-0.9516,122.7875,Hotel Santika Luwuk
33,Bengkulu,ID,79.41,broken clouds,-3.8004,102.2655,Grage Hotel Bengkulu
...,...,...,...,...,...,...,...
702,Atasu,KZ,84.52,overcast clouds,48.6814,71.6433,Dostyk
704,Lorengau,PG,82.11,scattered clouds,-2.0226,147.2712,Lorengau Harbourside Hotel
707,Atar,MR,77.72,moderate rain,20.5169,-13.0499,Oumou Elghoura
711,Monrovia,LR,76.91,clear sky,6.3005,-10.7969,Sunset Inn
713,Pishin,PK,80.38,clear sky,30.5803,66.9961,City Hotel Pishin

In [20]:
# 7. Drop the rows where there is no Hotel Name.
clean_hotel_df = hotel_df.loc[(hotel_df["Hotel Name"]!="")]
clean_hotel_df

,City,Country,Max Temp,Weather Description,Lat,Lng,Hotel Name
22,Benghazi,LY,75.58,clear sky,32.1167,20.0667,Tibesti Hotel
24,Bintulu,MY,84.61,scattered clouds,3.1667,113.0333,900 Boutique INN
28,Katsuura,JP,75.45,overcast clouds,35.1333,140.3000,Katsuura Hotel Mikazuki
32,Luwuk,ID,80.92,overcast clouds,-0.9516,122.7875,Hotel Santika Luwuk
33,Bengkulu,ID,79.41,broken clouds,-3.8004,102.2655,Grage Hotel Bengkulu
...,...,...,...,...,...,...,...
702,Atasu,KZ,84.52,overcast clouds,48.6814,71.6433,Dostyk
704,Lorengau,PG,82.11,scattered clouds,-2.0226,147.2712,Lorengau Harbourside Hotel
707,Atar,MR,77.72,moderate rain,20.5169,-13.0499,Oumou Elghoura
711,Monrovia,LR,76.91,clear sky,6.3005,-10.7969,Sunset Inn
713,Pishin,PK,80.38,clear sky,30.5803,66.9961,City Hotel Pishin

In [21]:
# 8a. Create the output File (CSV)
output_data_file = "vacation_search/WeatherPy_vacation.csv"

# 8b. Export the City_Data into a csv
clean_hotel_df.to_csv(output_data_file, index_label="City_ID")

In [22]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Weather Description</dt><dd>{Weather Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in clean_hotel_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = clean_hotel_df[["Lat", "Lng"]]

In [24]:
# 11a. Add a marker layer for each city to the map.

fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)

marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)

fig.add_layer(marker_layer)

# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))